### ISSUE TITLE
Добавление датчика HM3301 

### ISSUE THREAD

**Issue by MazurenkoEvgeniy** [andvikt/mega_hacs#102]
Можете добавить поддержку датчика HM3301?

Сейчас по ссылке вида http://192.168.0.14/sec/?pt=35&scl=34&i2c_dev=hm3301 выдается строка "pm1:9/pm2.5:13/pm10:17".

**Comment by andvikt** [comment]
> HM3301

В офиц инструкции нет информации о том как общаться с этим датчиком.

Без описания в формате как на скриншоте я не смогу добавить его поддержку

![image](https://user-images.githubusercontent.com/39195436/151700699-b9065830-52bd-44fa-8a7b-91d2c194e4a5.png)

**Comment by MazurenkoEvgeniy** [comment]
Отображение взвешенных частиц
http://192.168.0.14/sec/?pt=31&scl=30&i2c_dev=hm3301

Возвращает строку "pm1:9/pm2.5:13/pm10:17", сразу 3 параметра, по одному параметру обратиться нельзя.
Строку только разбивать на подстроки.
Содержит следующие параметры и их значения.

pm1 в примере значение 9
pm2.5 в примере значение 13
pm10 в примере значение 17

**Comment by MazurenkoEvgeniy** [comment]
Скорее всего автоматически определить датчик не получится, только через ручное добавление чрез конфиг.

**Comment by andvikt** [comment]
> Отображение взвешенных частиц http://192.168.0.14/sec/?pt=31&scl=30&i2c_dev=hm3301
> 
> Возвращает строку "pm1:9/pm2.5:13/pm10:17", сразу 3 параметра, по одному параметру обратиться нельзя. Строку только разбивать на подстроки. Содержит следующие параметры и их значения.
> 
> pm1 в примере значение 9 pm2.5 в примере значение 13 pm10 в примере значение 17
> 
> Скорее всего автоматически определить датчик не получится, только через ручное добавление чрез конфиг.

Странно, что в этом датчике сделано так, а не как во всех остальных.

Остальные датчики работают по принципу "одному параметру - один url". В данном случае, у вас на http://192.168.0.14/sec/?pt=31&scl=30&i2c_dev=hm3301 прилетает сразу все параметры, хотя должны были быть разбиты например так:
```
http://192.168.0.14/sec/?pt=31&scl=30&i2c_dev=hm3301
http://192.168.0.14/sec/?pt=31&scl=30&i2c_dev=hm3301&i2c_par=1
http://192.168.0.14/sec/?pt=31&scl=30&i2c_dev=hm3301&i2c_par=2
```
Схему с разбитием строки на несколько датчиков я поддерживать не буду, по крайней мере не сейчас, тк это потребует значительной доработки кода.

Если очень хочется повлиять, напишите Андрею свою просьбу оформить работу этого датчика в соответсвии с его же стандартным api, те на каждый параметр - свой url. Но что-то мне подсказывает, что это технически на стороне меги тоже сложно, скорее всего китайцы, производящие этот датчик, именно так и отдают его значение, а заниматься парсингом строк на контроллере видимо тоже никто заниматься не хочет )

Вы же можете решить эту историю стандартной интеграцией template. Например так:
```yaml
template:
  - trigger:
      - platform: state
        entity_id: sensor.mega_sensor  # entity_id сенсора меги в котором содержатся текстовые значения
    sensor:
      - name: "PM1"
        id: some_unique_sensor
        state: >-
          {% set parsed = state('sensor.mega_sensor').split('/')[0].split(':')[1] %}  
          {{parsed}}
        unit_of_measurement: "%"
``` 

Работу темплейта не проверял, но должно что-то в этом духе должно сработать
