### ISSUE TITLE
Не получается задать отрицательное число в `filter_low` для интеграции

### ISSUE THREAD

**Issue by leonidboykov** [andvikt/mega_hacs#145]
**Описание**

Не получается задать [`filter_low`](https://andvikt.github.io/mega_hacs/yaml/#filter_low) (как глобальное значение для интеграции).

``` yaml
mega:
  filter_high: 100
  filter_low: -100
```

Выдает такую ошибку:
> Invalid config for [mega]: expected a dictionary for dictionary value @ data['mega']['filter_high']. Got 100
expected a dictionary for dictionary value @ data['mega']['filter_low']. Got -100. (See /config/configuration.yaml, line 26).

Работает только если указать ID меги (кажется, что это противоречит документации, но я не уверен):

``` yaml
mega:
  mega:
    filter_high: 100
    filter_low: -100
```

Ругается только на отрицательное значение в `filter_low`:

> Invalid config for [mega]: value must be at least 0 for dictionary value @ data['mega']['mega']['filter_low']. Got -100. (See /config/configuration.yaml, line 26).

**Версии систем**
Environment: docker
HA version: 2023.4.4
mega_hacs version: v1.1.4
megad firmware version: 3.57b1
используется mqtt: false

**Ожидаемое поведение**
Можно задать отрицательное значение по умолчанию для `filter_low`.

**Comment by andvikt** [comment]
ошибка не в отрицательном значении, а в форме записи. вариант с id меги правильный

**Comment by leonidboykov** [comment]
@andvikt так даже в таком формате не задать отрицательное число:

``` yaml
mega:
  mega:
    filter_high: 100
    filter_low: -100 # Тут нельзя использовать отрицательное число.
```
