### ISSUE TITLE
прошу добавить датчик CO2 - SCD4x

### ISSUE THREAD

**Issue by xenus206** [andvikt/mega_hacs#146]
Подробное описание есть на сайте контроллера.
https://ab-log.ru/smart-house/ethernet/MegaD-2561-SCD4x

Спасибо.

**Comment by iliorik** [comment]
Добрый день.
Нужно добавить сенсор sdc4x.
Пока что временно я попробовал добавить

в файл: custom_components/mega/i2c.py
....
i2c_classes = {
'scd4x': [
DeviceType(None, None, 'ch0'),
],
'htu21d': [
.....
в файл: configuration.yaml
_#sch40x mega sensor
template:
sensor:
name: "Kithen_CO2"
unit_of_measurement: "ppm"
state: >
{% set sdc40_json = {
"carbon_dioxide": states('sensor.mega_10_scd4x_ch0').split("/")[0].split(":")[1]
} %}
{{ sdc40_json.carbon_dioxide }}
availability: "{{ ai_number(states('sensor.mega_10_scd4x_humidity')) }}"
name: "Kitchen_temp"
unit_of_measurement: "°C"
state: >
{% set sdc40_json = {
"carbon_dioxide": states('sensor.mega_10_scd4x_ch0').split("/")[1].split(":")[1]
} %}
{{ sdc40_json.carbon_dioxide }}
availability: "{{ ai_number(states('sensor.mega_10_scd4x_humidity')) }}"
name: "Kitchen_hum"
unit_of_measurement: "%"
state: >
{% set sdc40_json = {
"carbon_dioxide": states('sensor.mega_10_scd4x_ch0').split("/")[2].split(":")[1]
} %}
{{ sdc40_json.carbon_dioxide }}
availability: "{{ ai_number(states('sensor.mega_10_scd4x_humidity')) }}"_

**Comment by pavelplus** [comment]
Поддерживаю этот запрос! Датчик измеряет CO2, температуру и влажность и возвращает данные в формате: `CO2:969/temp:25.88/hum:60.55`.

При этом: 
>Сенсор обновляет данные каждые 5 секунд. Если все же произвести повторной запрос ранее, чем через 5 секунд после предыдущего, датчик вернет статус "busy".

Как еще один способ временного решения проблемы (без  необходимости править файл интеграции) можно опрашивать датчик напрямую средствами HA ([RESTful Sensor](https://www.home-assistant.io/integrations/sensor.rest)). Адрес resourse проще всего скопировать прямо из интерфейса контроллера. Проверки на "busy" тут нет.

```
# Wallmount sensor SCD4x - no support in megaD integration
rest:
  - resource: "http://MEGAD_IP/PASSWORD/?pt=PORT&scl=SCL_PORT&i2c_dev=scd4x"
    sensor:
      - name: "SCD4x_CO2"
        value_template: "{{ value.split('/')[0].split(':')[1] }}"
      - name: "SCD4x_temp"
        value_template: "{{ value.split('/')[1].split(':')[1] }}"
      - name: "SCD4x_hum"
        value_template: "{{ value.split('/')[2].split(':')[1] }}"
```
