### ISSUE TITLE
ADC Support

### ISSUE THREAD

**Issue by dramenev** [andvikt/mega_hacs#5]
**Описание**
Аналоговые датчики, подключенные к порту с типом ADC, не определяются интеграцией

**Версии систем**
Enviroment: raspberry/docker
HA version: 2021.1.5
mega_hacs version: 1.10.1
megad firmware version: 4.47b9

**Ожидаемое поведение**
Автоопределение датчиков с Type = ADC
Было бы здорово, если бы можно было еще задать шаблон конвертации оригинального значения в кастомизации

**Comment by andvikt** [comment]
Готово, версия 0.3.11

Шаблоны тоже сделал:
```yaml
# configuration.yaml
mega:
  hello: # ID меги, как в UI 
    36:
      # можно так же указать шаблон для конвертации значения, может быть полезно для ацп-входа
      # текущее значение порта передается в шаблон в переменной "value"
      conv_template: "{{(value|float)/100}}"

```
