### ISSUE TITLE
Новый стиль yaml-конфигурации 

### ISSUE THREAD

**Issue by andvikt** [andvikt/mega_hacs#71]
**Описание**
Добавить в yaml-конфиг упрощенный способ определения Domain и skip, чтобы полностью отказаться от неудобной схемы конфигурации.

Новая схема должна выглядеть так:

```yaml
mega:
  skip: [1, 2, 6, 8]
  switch: [10, 15, 16]
  entities: 
    light.some_light:
      # конфиг
```
